### ISSUE TITLE
Normalize bug

### ISSUE THREAD

**Issue by lnarmour** [CSU-CS-Melange/alpha-language#44]
This issue is to track a subtle EMF containment issue that Normalize encounters. We have a “fix" currently but we can’t pintpoint the root cause and can’t explain why the fix does what it does.

## Steps to reproduce

Take this progam: [tests/alpha.model.tests/resources/src-valid/reuse-analysis/rnaMEA.alpha](https://github.com/CSU-CS-Melange/alpha-language/blob/09f87aed645b84486219e013bb03009e6a1add2e/tests/alpha.model.tests/resources/src-valid/reuse-analysis/rnaMEA.alpha)

1. load the program and run `OptimalSimplifyingReductions.apply(“MEA", 5)`
2. observe that everything works
3. checkout the version of Normalize prior to this fix. The fix is in commit 598921ac.
```
git checkout 598921ac^1 -- bundles/alpha.model/src/alpha/model/transformation/Normalize.xtend
```
4. rerun OptimalSimplifyingReductions
5. observe that containment gets broken at some point.
```
Exception in thread "main" java.lang.RuntimeException: Uncontained AlphaExpression
	at alpha.model.ContextDomainCalculator.inAlphaExpression(ContextDomainCalculator.java:127)
	at alpha.model.util.DefaultAlphaExpressionVisitor.inCaseExpression(DefaultAlphaExpressionVisitor.java:294)
	at alpha.model.util.DefaultAlphaExpressionVisitor.visitCaseExpression(DefaultAlphaExpressionVisitor.java:99)
	at alpha.model.impl.CaseExpressionImpl.accept(CaseExpressionImpl.java:137)
	at alpha.model.ContextDomainCalculator._calculate(ContextDomainCalculator.java:45)
	at alpha.model.ContextDomainCalculator.calculate(ContextDomainCalculator.java:215)
	at alpha.model.AlphaInternalStateConstructor.recomputeContextDomain(AlphaInternalStateConstructor.java:84)
	at alpha.model.AlphaInternalStateConstructor.recomputeContextDomain(AlphaInternalStateConstructor.java:69)
	at alpha.model.transformation.Normalize._binaryExpressionRules(Normalize.java:470)
	at alpha.model.transformation.Normalize.binaryExpressionRules(Normalize.java:872)
	at alpha.model.transformation.Normalize.outBinaryExpression(Normalize.java:419)
	at alpha.model.util.DefaultAlphaExpressionVisitor.visitBinaryExpression(DefaultAlphaExpressionVisitor.java:205)
	at alpha.model.impl.BinaryExpressionImpl.accept(BinaryExpressionImpl.java:207)
	at alpha.model.util.DefaultAlphaExpressionVisitor.accept(DefaultAlphaExpressionVisitor.java:75)
	at alpha.model.transformation.Normalize._reapply(Normalize.java:210)
	at alpha.model.transformation.Normalize.reapply(Normalize.java:815)
	at alpha.model.transformation.Normalize.outBinaryExpression(Normalize.java:423)
	at alpha.model.util.DefaultAlphaExpressionVisitor.visitBinaryExpression(DefaultAlphaExpressionVisitor.java:205)
	at alpha.model.impl.BinaryExpressionImpl.accept(BinaryExpressionImpl.java:207)
	at alpha.model.util.DefaultAlphaExpressionVisitor.accept(DefaultAlphaExpressionVisitor.java:75)
	at alpha.model.util.DefaultAlphaExpressionVisitor.visitBinaryExpression(DefaultAlphaExpressionVisitor.java:203)
	at alpha.model.impl.BinaryExpressionImpl.accept(BinaryExpressionImpl.java:207)
	at alpha.model.util.DefaultAlphaExpressionVisitor.accept(DefaultAlphaExpressionVisitor.java:75)
	at alpha.model.util.AbstractAlphaCompleteVisitor.visitStandardEquation(AbstractAlphaCompleteVisitor.java:14)
	at alpha.model.impl.StandardEquationImpl.accept(StandardEquationImpl.java:207)
	at alpha.model.util.DefaultAlphaVisitor.lambda$7(DefaultAlphaVisitor.java:71)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at alpha.model.util.DefaultAlphaVisitor.visitSystemBody(DefaultAlphaVisitor.java:71)
	at alpha.model.impl.SystemBodyImpl.accept(SystemBodyImpl.java:266)
	at alpha.model.transformation.Normalize.apply(Normalize.java:193)
	at alpha.model.transformation.Normalize.apply(Normalize.java:188)
	at alpha.model.transformation.automation.OptimalSimplifyingReductions.preprocessing(OptimalSimplifyingReductions.java:370)
	at alpha.model.transformation.automation.OptimalSimplifyingReductions.run(OptimalSimplifyingReductions.java:390)
	at alpha.model.transformation.automation.OptimalSimplifyingReductions.apply(OptimalSimplifyingReductions.java:351)
	at alpha.model.transformation.automation.OptimalSimplifyingReductions.apply(OptimalSimplifyingReductions.java:338)
	at louis.hook.Lock.main(Lock.java:64)
```

## todo

Figure out why the changes in commit 598921ac resolve the issue and clean up the fix.

**Comment by ryanjob42** [comment]
Fixed by PR #56
